<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FrontendFaqsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('frontend_faqs')->delete();
        
        \DB::table('frontend_faqs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'question' => 'What is the quality of the content generated by AI?',
                'answer' => 'Our AI is trained on a diverse range of high-quality content, ensuring the generation of engaging, well-crafted, and top-notch content.',
            ),
            1 => 
            array (
                'id' => 2,
                'question' => 'Can I customize the content generated by AI to suit my needs?',
                'answer' => 'Absolutely! Our AI content generator provides advanced customization options. You can adjust the tone, style, length, and even provide specific instructions to tailor the generated content according to your requirements.',
            ),
            2 => 
            array (
                'id' => 3,
                'question' => 'Do I retain the copyright for the content generated by AI?',
                'answer' => 'Yes, you retain full copyright ownership of the content generated by our AI. You are free to use, modify, and publish the content as per your needs without any restrictions.',
            ),
            3 => 
            array (
                'id' => 4,
                'question' => 'How can I integrate the AI-generated content into my website or social media platforms?',
                'answer' => 'Our AI content generator allows you to download the generated content in text format or copy it directly. You can easily integrate it into your website or share it on your social media platforms, just like any other content.',
            ),
            4 => 
            array (
                'id' => 5,
                'question' => 'How can I measure the performance of the AI-generated content?',
                'answer' => 'We provide built-in analytics tools to track the performance of the AI-generated content. You can gather insights on clicks, conversions, engagement, and other relevant metrics to evaluate the effectiveness of your content.',
            ),
        ));
        
        
    }
}