<option value="{{$user->country}}" selected>{{$user->country?? 'Select Country'}}</option>

<option value="Afghanistan">{{__('Afghanistan')}}</option>
<option value="Åland Islands">{{__('Åland Islands')}}</option>
<option value="Albania">{{__('Albania')}}</option>
<option value="Algeria">{{__('Algeria')}}</option>
<option value="American Samoa">{{__('American Samoa')}}</option>
<option value="Andorra">{{__('Andorra')}}</option>
<option value="Angola">{{__('Angola')}}</option>
<option value="Anguilla">{{__('Anguilla')}}</option>
<option value="Antarctica">{{__('Antarctica')}}</option>
<option value="Antigua and Barbuda">{{__('Antigua and Barbuda')}}</option>
<option value="Argentina">{{__('Argentina')}}</option>
<option value="Armenia">{{__('Armenia')}}</option>
<option value="Aruba">{{__('Aruba')}}</option>
<option value="Australia">{{__('Australia')}}</option>
<option value="Austria">{{__('Austria')}}</option>
<option value="Azerbaijan">{{__('Azerbaijan')}}</option>
<option value="Bahamas">{{__('Bahamas')}}</option>
<option value="Bahrain">{{__('Bahrain')}}</option>
<option value="Bangladesh">{{__('Bangladesh')}}</option>
<option value="Barbados">{{__('Barbados')}}</option>
<option value="Belarus">{{__('Belarus')}}</option>
<option value="Belgium">{{__('Belgium')}}</option>
<option value="Belize">{{__('Belize')}}</option>
<option value="Benin">{{__('Benin')}}</option>
<option value="Bermuda">{{__('Bermuda')}}</option>
<option value="Bhutan">{{__('Bhutan')}}</option>
<option value="Bolivia">{{__('Bolivia')}}</option>
<option value="Bosnia and Herzegovina">{{__('Bosnia and Herzegovina')}}</option>
<option value="Botswana">{{__('Botswana')}}</option>
<option value="Bouvet Island">{{__('Bouvet Island')}}</option>
<option value="Brazil">{{__('Brazil')}}</option>
<option value="British Indian Ocean Territory">{{__('British Indian Ocean Territory')}}</option>
<option value="Brunei Darussalam">{{__('Brunei Darussalam')}}</option>
<option value="Bulgaria">{{__('Bulgaria')}}</option>
<option value="Burkina Faso">{{__('Burkina Faso')}}</option>
<option value="Burundi">{{__('Burundi')}}</option>
<option value="Cambodia">{{__('Cambodia')}}</option>
<option value="Cameroon">{{__('Cameroon')}}</option>
<option value="Canada">{{__('Canada')}}</option>
<option value="Cape Verde">{{__('Cape Verde')}}</option>
<option value="Cayman Islands">{{__('Cayman Islands')}}</option>
<option value="Central African Republic">{{__('Central African Republic')}}</option>
<option value="Chad">{{__('Chad')}}</option>
<option value="Chile">{{__('Chile')}}</option>
<option value="China">{{__('China')}}</option>
<option value="Christmas Island">{{__('Christmas Island')}}</option>
<option value="Cocos (Keeling) Islands">{{__('Cocos (Keeling) Islands')}}</option>
<option value="Colombia">{{__('Colombia')}}</option>
<option value="Comoros">{{__('Comoros')}}</option>
<option value="Congo">{{__('Congo')}}</option>
<option value="Congo, The Democratic Republic of The">{{__('Congo, The Democratic Republic of The')}}</option>
<option value="Cook Islands">{{__('Cook Islands')}}</option>
<option value="Costa Rica">{{__('Costa Rica')}}</option>
<option value="Cote D'ivoire">{{__('Cote D\'ivoire')}}</option>
<option value="Croatia">{{__('Croatia')}}</option>
<option value="Cuba">{{__('Cuba')}}</option>
<option value="Cyprus">{{__('Cyprus')}}</option>
<option value="Czech Republic">{{__('Czech Republic')}}</option>
<option value="Denmark">{{__('Denmark')}}</option>
<option value="Djibouti">{{__('Djibouti')}}</option>
<option value="Dominica">{{__('Dominica')}}</option>
<option value="Dominican Republic">{{__('Dominican Republic')}}</option>
<option value="Ecuador">{{__('Ecuador')}}</option>
<option value="Egypt">{{__('Egypt')}}</option>
<option value="El Salvador">{{__('El Salvador')}}</option>
<option value="Equatorial Guinea">{{__('Equatorial Guinea')}}</option>
<option value="Eritrea">{{__('Eritrea')}}</option>
<option value="Estonia">{{__('Estonia')}}</option>
<option value="Ethiopia">{{__('Ethiopia')}}</option>
<option value="Falkland Islands (Malvinas)">{{__('Falkland Islands (Malvinas')}})</option>
<option value="Faroe Islands">{{__('Faroe Islands')}}</option>
<option value="Fiji">{{__('Fiji')}}</option>
<option value="Finland">{{__('Finland')}}</option>
<option value="France">{{__('France')}}</option>
<option value="French Guiana">{{__('French Guiana')}}</option>
<option value="French Polynesia">{{__('French Polynesia')}}</option>
<option value="French Southern Territories">{{__('French Southern Territories')}}</option>
<option value="Gabon">{{__('Gabon')}}</option>
<option value="Gambia">{{__('Gambia')}}</option>
<option value="Georgia">{{__('Georgia')}}</option>
<option value="Germany">{{__('Germany')}}</option>
<option value="Ghana">{{__('Ghana')}}</option>
<option value="Gibraltar">{{__('Gibraltar')}}</option>
<option value="Greece">{{__('Greece')}}</option>
<option value="Greenland">{{__('Greenland')}}</option>
<option value="Grenada">{{__('Grenada')}}</option>
<option value="Guadeloupe">{{__('Guadeloupe')}}</option>
<option value="Guam">{{__('Guam')}}</option>
<option value="Guatemala">{{__('Guatemala')}}</option>
<option value="Guernsey">{{__('Guernsey')}}</option>
<option value="Guinea">{{__('Guinea')}}</option>
<option value="Guinea-bissau">{{__('Guinea-bissau')}}</option>
<option value="Guyana">{{__('Guyana')}}</option>
<option value="Haiti">{{__('Haiti')}}</option>
<option value="Heard Island and Mcdonald Islands">{{__('Heard Island and Mcdonald Islands')}}</option>
<option value="Holy See (Vatican City State)">{{__('Holy See (Vatican City State')}})</option>
<option value="Honduras">{{__('Honduras')}}</option>
<option value="Hong Kong">{{__('Hong Kong')}}</option>
<option value="Hungary">{{__('Hungary')}}</option>
<option value="Iceland">{{__('Iceland')}}</option>
<option value="India">{{__('India')}}</option>
<option value="Indonesia">{{__('Indonesia')}}</option>
<option value="Iran, Islamic Republic of">{{__('Iran, Islamic Republic of')}}</option>
<option value="Iraq">{{__('Iraq')}}</option>
<option value="Ireland">{{__('Ireland')}}</option>
<option value="Isle of Man">{{__('Isle of Man')}}</option>
<option value="Israel">{{__('Israel')}}</option>
<option value="Italy">{{__('Italy')}}</option>
<option value="Jamaica">{{__('Jamaica')}}</option>
<option value="Japan">{{__('Japan')}}</option>
<option value="Jersey">{{__('Jersey')}}</option>
<option value="Jordan">{{__('Jordan')}}</option>
<option value="Kazakhstan">{{__('Kazakhstan')}}</option>
<option value="Kenya">{{__('Kenya')}}</option>
<option value="Kiribati">{{__('Kiribati')}}</option>
<option value="Korea, Democratic People's Republic of">{{__('Korea, Democratic People\'s Republic of')}}</option>
<option value="Korea, Republic of">{{__('Korea, Republic of')}}</option>
<option value="Kuwait">{{__('Kuwait')}}</option>
<option value="Kyrgyzstan">{{__('Kyrgyzstan')}}</option>
<option value="Lao People's Democratic Republic">{{__('Lao People\'s Democratic Republic')}}</option>
<option value="Latvia">{{__('Latvia')}}</option>
<option value="Lebanon">{{__('Lebanon')}}</option>
<option value="Lesotho">{{__('Lesotho')}}</option>
<option value="Liberia">{{__('Liberia')}}</option>
<option value="Libyan Arab Jamahiriya">{{__('Libyan Arab Jamahiriya')}}</option>
<option value="Liechtenstein">{{__('Liechtenstein')}}</option>
<option value="Lithuania">{{__('Lithuania')}}</option>
<option value="Luxembourg">{{__('Luxembourg')}}</option>
<option value="Macao">{{__('Macao')}}</option>
<option value="Macedonia, The Former Yugoslav Republic of">{{__('Macedonia, The Former Yugoslav Republic of')}}</option>
<option value="Madagascar">{{__('Madagascar')}}</option>
<option value="Malawi">{{__('Malawi')}}</option>
<option value="Malaysia">{{__('Malaysia')}}</option>
<option value="Maldives">{{__('Maldives')}}</option>
<option value="Mali">{{__('Mali')}}</option>
<option value="Malta">{{__('Malta')}}</option>
<option value="Marshall Islands">{{__('Marshall Islands')}}</option>
<option value="Martinique">{{__('Martinique')}}</option>
<option value="Mauritania">{{__('Mauritania')}}</option>
<option value="Mauritius">{{__('Mauritius')}}</option>
<option value="Mayotte">{{__('Mayotte')}}</option>
<option value="Mexico">{{__('Mexico')}}</option>
<option value="Micronesia, Federated States of">{{__('Micronesia, Federated States of')}}</option>
<option value="Moldova, Republic of">{{__('Moldova, Republic of')}}</option>
<option value="Monaco">{{__('Monaco')}}</option>
<option value="Mongolia">{{__('Mongolia')}}</option>
<option value="Montenegro">{{__('Montenegro')}}</option>
<option value="Montserrat">{{__('Montserrat')}}</option>
<option value="Morocco">{{__('Morocco')}}</option>
<option value="Mozambique">{{__('Mozambique')}}</option>
<option value="Myanmar">{{__('Myanmar')}}</option>
<option value="Namibia">{{__('Namibia')}}</option>
<option value="Nauru">{{__('Nauru')}}</option>
<option value="Nepal">{{__('Nepal')}}</option>
<option value="Netherlands">{{__('Netherlands')}}</option>
<option value="Netherlands Antilles">{{__('Netherlands Antilles')}}</option>
<option value="New Caledonia">{{__('New Caledonia')}}</option>
<option value="New Zealand">{{__('New Zealand')}}</option>
<option value="Nicaragua">{{__('Nicaragua')}}</option>
<option value="Niger">{{__('Niger')}}</option>
<option value="Nigeria">{{__('Nigeria')}}</option>
<option value="Niue">{{__('Niue')}}</option>
<option value="Norfolk Island">{{__('Norfolk Island')}}</option>
<option value="Northern Mariana Islands">{{__('Northern Mariana Islands')}}</option>
<option value="Norway">{{__('Norway')}}</option>
<option value="Oman">{{__('Oman')}}</option>
<option value="Pakistan">{{__('Pakistan')}}</option>
<option value="Palau">{{__('Palau')}}</option>
<option value="Palestinian Territory, Occupied">{{__('Palestinian Territory, Occupied')}}</option>
<option value="Panama">{{__('Panama')}}</option>
<option value="Papua New Guinea">{{__('Papua New Guinea')}}</option>
<option value="Paraguay">{{__('Paraguay')}}</option>
<option value="Peru">{{__('Peru')}}</option>
<option value="Philippines">{{__('Philippines')}}</option>
<option value="Pitcairn">{{__('Pitcairn')}}</option>
<option value="Poland">{{__('Poland')}}</option>
<option value="Portugal">{{__('Portugal')}}</option>
<option value="Puerto Rico">{{__('Puerto Rico')}}</option>
<option value="Qatar">{{__('Qatar')}}</option>
<option value="Reunion">{{__('Reunion')}}</option>
<option value="Romania">{{__('Romania')}}</option>
<option value="Russian Federation">{{__('Russian Federation')}}</option>
<option value="Rwanda">{{__('Rwanda')}}</option>
<option value="Saint Helena">{{__('Saint Helena')}}</option>
<option value="Saint Kitts and Nevis">{{__('Saint Kitts and Nevis')}}</option>
<option value="Saint Lucia">{{__('Saint Lucia')}}</option>
<option value="Saint Pierre and Miquelon">{{__('Saint Pierre and Miquelon')}}</option>
<option value="Saint Vincent and The Grenadines">{{__('Saint Vincent and The Grenadines')}}</option>
<option value="Samoa">{{__('Samoa')}}</option>
<option value="San Marino">{{__('San Marino')}}</option>
<option value="Sao Tome and Principe">{{__('Sao Tome and Principe')}}</option>
<option value="Saudi Arabia">{{__('Saudi Arabia')}}</option>
<option value="Senegal">{{__('Senegal')}}</option>
<option value="Serbia">{{__('Serbia')}}</option>
<option value="Seychelles">{{__('Seychelles')}}</option>
<option value="Sierra Leone">{{__('Sierra Leone')}}</option>
<option value="Singapore">{{__('Singapore')}}</option>
<option value="Slovakia">{{__('Slovakia')}}</option>
<option value="Slovenia">{{__('Slovenia')}}</option>
<option value="Solomon Islands">{{__('Solomon Islands')}}</option>
<option value="Somalia">{{__('Somalia')}}</option>
<option value="South Africa">{{__('South Africa')}}</option>
<option value="South Georgia and The South Sandwich Islands">{{__('South Georgia and The South Sandwich Islands')}}</option>
<option value="Spain">{{__('Spain')}}</option>
<option value="Sri Lanka">{{__('Sri Lanka')}}</option>
<option value="Sudan">{{__('Sudan')}}</option>
<option value="Suriname">{{__('Suriname')}}</option>
<option value="Svalbard and Jan Mayen">{{__('Svalbard and Jan Mayen')}}</option>
<option value="Swaziland">{{__('Swaziland')}}</option>
<option value="Sweden">{{__('Sweden')}}</option>
<option value="Switzerland">{{__('Switzerland')}}</option>
<option value="Syrian Arab Republic">{{__('Syrian Arab Republic')}}</option>
<option value="Taiwan">{{__('Taiwan')}}</option>
<option value="Tajikistan">{{__('Tajikistan')}}</option>
<option value="Tanzania, United Republic of">{{__('Tanzania, United Republic of')}}</option>
<option value="Thailand">{{__('Thailand')}}</option>
<option value="Timor-leste">{{__('Timor-leste')}}</option>
<option value="Togo">{{__('Togo')}}</option>
<option value="Tokelau">{{__('Tokelau')}}</option>
<option value="Tonga">{{__('Tonga')}}</option>
<option value="Trinidad and Tobago">{{__('Trinidad and Tobago')}}</option>
<option value="Tunisia">{{__('Tunisia')}}</option>
<option value="Turkey">{{__('Turkey')}}</option>
<option value="Turkmenistan">{{__('Turkmenistan')}}</option>
<option value="Turks and Caicos Islands">{{__('Turks and Caicos Islands')}}</option>
<option value="Tuvalu">{{__('Tuvalu')}}</option>
<option value="Uganda">{{__('Uganda')}}</option>
<option value="Ukraine">{{__('Ukraine')}}</option>
<option value="United Arab Emirates">{{__('United Arab Emirates')}}</option>
<option value="United Kingdom">{{__('United Kingdom')}}</option>
<option value="United States">{{__('United States')}}</option>
<option value="United States Minor Outlying Islands">{{__('United States Minor Outlying Islands')}}</option>
<option value="Uruguay">{{__('Uruguay')}}</option>
<option value="Uzbekistan">{{__('Uzbekistan')}}</option>
<option value="Vanuatu">{{__('Vanuatu')}}</option>
<option value="Venezuela">{{__('Venezuela')}}</option>
<option value="Viet Nam">{{__('Viet Nam')}}</option>
<option value="Virgin Islands, British">{{__('Virgin Islands, British')}}</option>
<option value="Virgin Islands, U.S.">{{__('Virgin Islands, U.S')}}.</option>
<option value="Wallis and Futuna">{{__('Wallis and Futuna')}}</option>
<option value="Western Sahara">{{__('Western Sahara')}}</option>
<option value="Yemen">{{__('Yemen')}}</option>
<option value="Zambia">{{__('Zambia')}}</option>
<option value="Zimbabwe">{{__('Zimbabwe')}}</option>
